<template>
<div>
  <h2>分类</h2>
  <ul>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
    <li>滚动测试</li>
  </ul>
  </div>
</template>

<script>
  export default {
    name: "Category"
  }
</script>

<style scoped>

</style>
